//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tank {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tank.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bullet.x3m.
        /// </summary>
        internal static string BulletModelFile {
            get {
                return ResourceManager.GetString("BulletModelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string ClientTag {
            get {
                return ResourceManager.GetString("ClientTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load data from &apos;{0}&apos;.
        /// </summary>
        internal static string DataLoadError {
            get {
                return ResourceManager.GetString("DataLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data.
        /// </summary>
        internal static string DataPath {
            get {
                return ResourceManager.GetString("DataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling display list #{0}....
        /// </summary>
        internal static string DisplayListCompiling {
            get {
                return ResourceManager.GetString("DisplayListCompiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine.
        /// </summary>
        internal static string EngineTag {
            get {
                return ResourceManager.GetString("EngineTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering the main loop....
        /// </summary>
        internal static string EnterMainLoop {
            get {
                return ResourceManager.GetString("EnterMainLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string EventTag {
            get {
                return ResourceManager.GetString("EventTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting the main loop....
        /// </summary>
        internal static string ExitMainLoop {
            get {
                return ResourceManager.GetString("ExitMainLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to start the game. Technical details:.
        /// </summary>
        internal static string InitializationError {
            get {
                return ResourceManager.GetString("InitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1}.
        /// </summary>
        internal static string LogInformationFormat {
            get {
                return ResourceManager.GetString("LogInformationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading model from file &apos;{0}&apos;....
        /// </summary>
        internal static string ModelLoading {
            get {
                return ResourceManager.GetString("ModelLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string ModelTag {
            get {
                return ResourceManager.GetString("ModelTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initailize the video renderer..
        /// </summary>
        internal static string RendererInitializationFailure {
            get {
                return ResourceManager.GetString("RendererInitializationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render.
        /// </summary>
        internal static string RendererTag {
            get {
                return ResourceManager.GetString("RendererTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tank_barrel.x3m.
        /// </summary>
        internal static string TankBarrelModelFile {
            get {
                return ResourceManager.GetString("TankBarrelModelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tank_base.x3m.
        /// </summary>
        internal static string TankBaseModelFile {
            get {
                return ResourceManager.GetString("TankBaseModelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add engine task because it already exists..
        /// </summary>
        internal static string TaskAddAlreadyExists {
            get {
                return ResourceManager.GetString("TaskAddAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove engine task because it does not exist..
        /// </summary>
        internal static string TaskRemoveDoesNotExist {
            get {
                return ResourceManager.GetString("TaskRemoveDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading texture from image file &apos;{0}&apos;....
        /// </summary>
        internal static string TextureLoading {
            get {
                return ResourceManager.GetString("TextureLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture.
        /// </summary>
        internal static string TextureTag {
            get {
                return ResourceManager.GetString("TextureTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OH MY GOD! Tanks encountered an unexpected error during execution..
        /// </summary>
        internal static string UnhandledExceptionMessage1 {
            get {
                return ResourceManager.GetString("UnhandledExceptionMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the boring technical details:.
        /// </summary>
        internal static string UnhandledExceptionMessage2 {
            get {
                return ResourceManager.GetString("UnhandledExceptionMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User requested a program quit.
        /// </summary>
        internal static string UserQuitRequest {
            get {
                return ResourceManager.GetString("UserQuitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing video....
        /// </summary>
        internal static string VideoInitializing {
            get {
                return ResourceManager.GetString("VideoInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down video....
        /// </summary>
        internal static string VideoShutdown {
            get {
                return ResourceManager.GetString("VideoShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank!.
        /// </summary>
        internal static string WindowCaption {
            get {
                return ResourceManager.GetString("WindowCaption", resourceCulture);
            }
        }
    }
}
